import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import SocialMedia from '../../../src/components/UI/SocialMedia';
import useFetch from '../../../src/hooks/useFetch';
import { episode } from '../../../src/models/detailSeriesSeason';

const EpisodeDetail: NextPage = () => {
  //   get the route
  const router = useRouter();
  const { episode } = router.query;

  //   extract the route
  const idAddress = episode?.toString().split(' ')[1];
  const numberOfSeason =
    episode && episode.toString().split(' ')[0].split('-')[1] === 'specials'
      ? 0
      : episode?.toString().split(' ')[0].split('-')[1];
  const numberOfEpisode = episode?.toString().split(' ')[0].split('-')[3];

  //   state of episode detail data
  const [episodeDetailData, setEpisodeDetailData] = useState<
    episode | undefined
  >(undefined);

  // fetching data
  const { isLoading: loadingEpisode } = useFetch(
    `https://api.themoviedb.org/3/tv/${idAddress}/season/${numberOfSeason}/episode/${numberOfEpisode}?api_key=639d75e6b806c03213815ae9aa5a9376&language=en-US`,
    idAddress,
    setEpisodeDetailData
  );

  return (
    <div className="w-full">
      <Head>
        <title>
          Season {numberOfSeason} - Episode {numberOfEpisode}
        </title>
        <meta
          name={
            episodeDetailData
              ? episodeDetailData.overview
              : 'Episode dari kumpulan Series-Series Populer dari berbagai genre dan berbagai production house ternama di dunia, seperti Disney, FOX, dan lain-lain'
          }
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {episodeDetailData && !loadingEpisode && (
        <>
          <div className="w-full py-5 px-10">
            <h1 className="text-2xl text-left font-bold text-primaryGrey">
              {episodeDetailData.name}
            </h1>
            <p className="text-md text-ternaryGrey my-5">
              {episodeDetailData.overview}
            </p>
            <div className="w-full py-5 border-y-[1px] border-y-secondaryGrey my-5">
              <div className="relative h-[210px] md:h-[360px] lg:h-[480px] xl:h-[640px]">
                <Image
                  src={`https://www.themoviedb.org/t/p/original${episodeDetailData.still_path}`}
                  alt={episodeDetailData.name}
                  fill
                  sizes="true"
                  priority
                />
              </div>
            </div>
            <div className="w-full flex items-center">
              <span className="text-sm text-ternaryGrey mr-5">
                {episodeDetailData.air_date}
              </span>
              <span className="text-sm text-ternaryGrey">
                Rating: {episodeDetailData.vote_average.toFixed(1)}
              </span>
            </div>
          </div>
          <SocialMedia />
        </>
      )}
    </div>
  );
};

export default EpisodeDetail;
