import type { NextPage } from 'next';
import Head from 'next/head';
import { ReactNode } from 'react';
import ContentCard from '../src/components/UI/ContentCard';

const Home: NextPage = () => {
  return (
    <div className="w-full p-5">
      <Head>
        <title>FELIX</title>
        <meta
          name="Situs penyedia informasi tentang film dan serial tv
            gratis. Sama seperti penyedia film dan serial tv lainnya seperti
            Netflix, Disney+, HBO, Apple TV+, Amazon Prime Video, dan lainnya."
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full border-b-[1px] border-b-secondaryGrey mb-5">
        <span className="px-3 py-1 w-full text-xl text-slate-200 border-l-[3px] border-l-primaryRed">
          FEATURED
        </span>
        <ul className="grid grid-cols-3 gap-3 mt-6 md:grid-cols-4 lg:grid-cols-6 lg:gap-7">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18].map(
            (item: number): ReactNode => (
              <ContentCard key={item + ''} />
            )
          )}
        </ul>
      </div>

      <div className="w-full border-b-[1px] border-b-secondaryGrey mb-5">
        <span className="px-3 py-1 w-full text-xl text-slate-200 border-l-[3px] border-l-primaryRed">
          MOVIES
        </span>
        <ul className="grid grid-cols-3 gap-3 mt-6 md:grid-cols-4 lg:grid-cols-6 lg:gap-7">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(
            (item: number): ReactNode => (
              <ContentCard key={item + ''} />
            )
          )}
        </ul>
      </div>

      <div className="w-full">
        <span className="px-3 py-1 w-full text-xl text-slate-200 border-l-[3px] border-l-primaryRed">
          MOVIES
        </span>
        <ul className="grid grid-cols-3 gap-3 mt-6 md:grid-cols-4 lg:grid-cols-6 lg:gap-7">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(
            (item: number): ReactNode => (
              <ContentCard key={item + ''} />
            )
          )}
        </ul>
      </div>
    </div>
  );
};

export default Home;
